- defaults:
    link:
        create: true
        relink: true

- create:
    '~/.ssh':
        mode: 0700

- clean: ['~', '~/.config']

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.shell:
    ~/.tmux.conf:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
